### PR TITLE
Don't assume addon is installed in home directory.

### PR DESCRIPTION
**Pull request by jfly**
Addons can actually be installed elsewhere. For example, Nix opts to
install them in `special://xbmc/addons/`.

I got this suggestion to use `addon.getAddonInfo('path')` from
https://forum.kodi.tv/showthread.php?tid=274751. It seems to do what
it's supposed to!

### CODE REVIEW

**Comment by aanderse** [comment]
Great change @jfly! Here is an example of another plugin which was modified in the same way: https://github.com/zach-morris/plugin.program.iagl/issues/231.

**Comment by anxdpanic** [comment]
@jfly Thank you for this!
 Can you change the f-string usage for string substitution, the code needs to be compat. with Python 2.6-7 and 3.x

**Comment by jfly** [comment]
> Can you change the f-string usage for string substitution, the code needs to be compat. with Python 2.6-7 and 3.x

Done, @anxdpanic!

**Comment by anxdpanic** [comment]
Thanks again!

**Pull request merged**
