### PR TITLE
Restore related videos, recommendations, and auto-play next functionality

### LINKED ISSUE #508: Recommendations empty & rightclick=>More=>Related Videos error
### Context
Recommendations is empty starting yesterday. 
And right-clicking a link when choosing **More=>Related Videos** produces an error
as in the screenshot below, debug log link below as well.
image

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.2
* Kodi GUI Language: English
* Operating System: Win 10 64 bit
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log
https://paste.kodi.tv/yukugisoco.kodi
Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

### LINKED ISSUE #549: Queuing from current playlist is broken
Libreelec 11.0.4, YouTube addon 7.0.2.2

### Steps to Reproduce

1. Start video playback of some YT video, queue more videos
2. Open playlist of queued videos
3. Select any of them and press Go to NAME_OF_THE_YT_CHANNEL from drop down menu
4. Queue video from that YT channel
5. Check again current playlist of queued videos

Problem: No videos were queued from that YT channel.

### PR DESCRIPTION
**Pull request by MoojMidge**
### Fixes:

- Fix #508
- Fix #549 

### New:

- Update main menu items:
  - New Recommended videos with similar content as YouTube home page (will use login details if available)
  - Old Recommended videos renamed to Related videos (requires either local or remote playback history enabled)
  - Popular right now renamed to Trending

### Changed:

- All existing local user data (local watch history, cache, etc.) will be lost due to updated storage format

### CODE REVIEW

**Comment by RNavega** [comment]
This is amazing, lots of work in this. Congratulations.

**Comment by MoojMidge** [comment]
Few updates to be made for cache and thread handling, but it works pretty well in comparison to my own manual viewing habits.

**Comment by misslisa62tx** [comment]
Recomendations and Related Videos both work for me, but MySubscriptions crashes with a Python error.  

My setup is Raspberry Pi4, RPI Bookworm (Debian 12), Kodi Nexus 20.3

[7.0.3-beta.1.Python Error.MySubscriptions.log](https://github.com/anxdpanic/plugin.video.youtube/files/13995079/7.0.3-beta.1.Python.Error.MySubscriptions.log)

**Comment by MoojMidge** [comment]
@misslisa62tx - https://github.com/anxdpanic/plugin.video.youtube/issues/555

**Pull request merged**
