### PR TITLE
Additional fixes for "The following content is not available on this app." error

### LINKED ISSUE #442: Video's don't play with "content not available on this app" error
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.1
* Kodi GUI Language: English
* Operating System: LibreELEC 11.01
* Operating System Language: English

------

### Expected Behavior

Video's play as normal.

------

### Current Behavior

Since this morning (Europe timezone), the Youtube plugin is unable to play any video's wth the error stating "Content not available on this app". Everything was working fine yesterday evening and into the night.

Disabling/enabling InputStream Adaptive for video playback makes no difference.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to play any video (e.g. from your subscription feed).
2. Get the error.

------

### Log

https://pastebin.com/4sn6gRgJ

------

### EDIT

**Fixed version:**
Alpha release appears to have resolved the majority of the issues so far:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/7.x.x-dev
Not in Stable branch (yet), so leaving the issue open until pushed to Stable branch.

**Potential (manual) Workaround(s):**
@RNavega provided a fix that seems to work for now:
https://github.com/anxdpanic/plugin.video.youtube/issues/442#issuecomment-1516245701
Specifically, the "payload" section seems to be the fix.

Another version of the fix to video_info.py which seems to be more reliable:
https://github.com/anxdpanic/plugin.video.youtube/issues/442#issuecomment-1526189381

### PR DESCRIPTION
**Pull request by MoojMidge**
There are still a few issues with the recent changes (#447 and #449) to try and fix #442

This is a further attempt to try and resolve the problem, extending the previous approach.

In my limited testing this resolves the original problem as well as the subsequent issues:
- Playback freezing after some short period of playback
- Playback freezing after skipping
- HD and greater resolutions not available with MPEG-DASH

Couple of notes:
- Haven't tested any live videos.
- The client fallback and authorization header fallback shouldn't be currently necessary (and the fallback doesn't occur in my testing using the updated `ANDROID` client details), but may be useful if similar issues occur in the future.
- If a fallback is used, perhaps this should be logged or a notification shown to highlight this? Additional client fallbacks could also be added.
- The `TV_UNPLUGGED_ANDROID` client appears to work but I didn't test it very much (it appears to be from an Android Youtube TV PVR app and according to https://github.com/zerodytrash/YouTube-Internal-Clients has less formats than the `ANDROID` client).
- I didn't test the authorization header removal at all. 
- Not sure if this is a reliable fix as people seem to be having varying levels of success with the original code and subsequent changes.
- There is a bunch of mostly unrelated formatting changes in this PR (in da99585ad94403d011f461eb5dbf172f058bda18). My editor/linter was bugging me about it, and I got half way through it before realising it was out of scope for this PR. I can remove the changes if needed.

### CODE REVIEW

**Comment by MoojMidge** [comment]
I added a few more fallbacks which should help with some videos that were previously unable to be played (restrictions on embedding, or requiring login/age verification)

However I noticed that some videos only have a `signatureCipher`, rather than an `url` in the stream details. Looks like support for deciphering these was removed in https://github.com/anxdpanic/plugin.video.youtube/commit/c7c2719d150a6df3cfff47e72fff230ffad77203

@RNavega do you know if the method for deciphering still works? Could it be added back for videos that require it?

**Comment by anxdpanic** [comment]
@MoojMidge Thanks for this

As long as these match the signature cipher should work
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1555-L1567
https://github.com/anxdpanic/plugin.video.youtube/tree/master/resources/lib/youtube_plugin/youtube/helper/signature#L116-L128

**Comment by MoojMidge** [comment]
All good. Looks like it hasn't fully resolved the problem though (works for me though `¯\_(ツ)_/¯`)

I haven't seen the issues with rate limiting re-occur just yet using the latest `ANDROID` or the `TVHTML5_SIMPLY_EMBEDDED_PLAYER` client details. Difficult to say exactly what is happening based on the mixed feedback in #442

I also didn't have much success with the `ANDROID_EMBEDDED_PLAYER` client details, but it appears to be working for others. Shall I add it in as another fallback? It would be another stop-gap until the signature deciphering was added back for use with the `WEB_CREATOR` client details.

**Comment by RNavega** [comment]
> RNavega do you know if the method for deciphering still works? Could it be added back for videos that require it?

@MoojMidge I'm not sure, to be honest. It's been a long time after this add-on started using the "spoof an Android client to get the unencrypted streams" trick that it took from Invidious, as it saves a lot of trouble.  
It's tough going back to deciphering as it's a cat-and-mouse thing, all it takes for things to break is them changing a small thing, since the deciphering is done with plaintext parsing and not evaluating the JS code for it.

The "ANDROID" client details were PR'ed by me, and after a few days of use I noticed that video cutoff problem as others did too (or in the case of others, their videos would freeze).  

I'm since back to using the ["ANDROID_EMBEDDED_PLAYER" details](https://github.com/anxdpanic/plugin.video.youtube/issues/442#issuecomment-1516245701), it has 360p and 720p which is enough for me, and I haven't noticed those playback problems.  
If I output the raw `player_response` from it, I can see that there are HD formats available too: https://gist.github.com/RNavega/f142a5be25e7374c42bd1e23183108ca

So definitely think trying this embedded name might be worth it.

PS if throttling ever becomes a problem again, there seems to be a new trick: adding a "&range=0-{contentLength}" parameter to the stream URL before requesting it: https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1455142084
In the case of Invidious this is done per chunk request (which mimics the official YT web player better): https://github.com/iv-org/invidious/pull/3674/commits/865b7e584d16aa8947b3f0449bf4c048ca01a7f4

**Comment by MoojMidge** [comment]
@anxdpanic I have re-added the signature deciphering for the `WEB_CREATOR` client fallback. Seems to still work fine and is still required for some otherwise restricted videos.

@RNavega the problem with using `ANDROID_EMBEDDED_PLAYER` is that the streams are limited to <720p as you noted (haven't looked into why) and some videos can't be played with an embedded client. With `ANDROID` I don't see any issues with freezing, dropping out, or seeking and I get 1080p and 4k streams. I have added `ANDROID_EMBEDDED_PLAYER` as a client fallback, but unless the requests fail with the other clients it won't be used.

I have also added the range query parameter, but I haven't looked into how the range header can be sent to InputStream.Adaptive, let's see if it improves the drop outs and seeking issues.

I'll open a new PR for the additional changes

**Comment by RNavega** [comment]
> the problem with using ANDROID_EMBEDDED_PLAYER is that the streams are limited to <720p as you noted (haven't looked into why)

The gist I linked to shows qualities above 720p, it's in the adaptiveFormats list:

> If I output the raw `player_response` from [ANDROID_EMBEDDED_PLAYER], I can see that there are HD formats available too: https://gist.github.com/RNavega/f142a5be25e7374c42bd1e23183108ca

**Comment by MoojMidge** [comment]
Yeah, some videos certainly have higher qualities, but 5 out of the first 10 videos in my Popular Right Now list are limited to 720p using `ANDROID_EMBEDDED_PLAYER` and a whole bunch of older favourited videos don't play at all (not really a problem because of the client fallbacks). On the other hand everything seems to be ok using the `ANDROID` client.

Perhaps the choice of client should be made into an advanced option?

**Comment by RNavega** [comment]
> Perhaps the choice of client should be made into an advanced option?

Yeah, given the many different experiences people are having (probably due to their geolocations), I think that's the only option. A new setting in the Advanced tab where they can pick the client/payload preset to use.

**Comment by MoojMidge** [comment]
I have added a boolean advanced option in #455. It just toggles between the `ANDROID_EMBEDDED_PLAYER` (default) and `ANDROID` clients, with the other client fallbacks automatically being used for restricted videos.

I also added the range query parameter but it didn't seem to make any difference for me. CURL component debug logging indicated that the range header was also being sent (not sure how, something in InputStream.Adaptive itself?).

Can you test if there is any improvement for you?

**Comment by RNavega** [comment]
> I also added the range query parameter but it didn't seem to make any difference for me. CURL component debug logging indicated that the range header was also being sent (not sure how, something in InputStream.Adaptive itself?).

When Kodi wants to play something it either asks FFMpeg to do it, or InputStream.Adaptive if the video item is set up to use it. So if you add that "range" as a URL parameter then it'll definitely be used by either of them, as it'll be part of the URL string.

> Can you test if there is any improvement for you?

Well, for me the embedded client was already enough, so if there's others like me then that default client should be useful.  
For transparency, in a personal copy I added a piped.video (similar to Invidious) fallback, for when a video doesn't want to play at all.

Thanks for working on #455.

**Comment by MoojMidge** [comment]
When the range query parameter is added it is just a static value i.e. `0-X`, where `X` is the content length from the `clen` query parameter. However the value for the range header is different to this. I am not too familiar with how the MPD handling actually works, but each request for each chunk/fragment has its own range header that gets added from somewhere (presumably InputStream.Adaptive).

The problem is that on some devices after 30s cURL closes the connection to the stream server and new connections fail with a 403 Forbidden error. Not sure if there is some fingerprinting or blacklisting happening, but a search of the usual places hasn't revealed any similar problems.

> For transparency, in a personal copy I added a piped.video (similar to Invidious) fallback, for when a video doesn't want to play at all.

That was the idea of using the fallbacks, but motivation is waning since I don't seem to have the same problems others are having, but it may just be a matter of time.

**Pull request merged**
