### PR TITLE
Client and stream processing updates

### LINKED ISSUE #501: Increasingly common 403 errors when casting videos
### Context

Please provide any relevant information about your setup

* Add-on Version: git master branch
* Kodi Version: Nexus
* Kodi GUI Language: English
* Operating System: Ubuntu Linux
* Operating System Language: English

Since about March, this plugin has worked great.  In the past few weeks, I've seen more and more instances where I send a video from Cast Kodi and a transient error occurs:

```
2023-08-07 21:37:36.347 T:921805   error <general>: CCurlFile::CReadState::FillBuffer - (0x7fbc7838bc20) Failed: HTTP returned code 403
2023-08-07 21:37:36.347 T:921805   error <general>: CCurlFile::Open - <https://rr1---sn-o097znsd.googlevideo.com/videoplayback?expire=1691490717&ei=PcXRZKO6IYz_kgaKoYMI&ip=2601%3A[REDACTED] Failed with code 403:
2023-08-07 21:37:36.347 T:921805   error <general>: CFileCache::Open - <https://rr1---sn-o097znsd.googlevideo.com/videoplayback?expire=1691490717&ei=[REDACTED]&ip=2601%3A[REDACTED]-> failed to open
2023-08-07 21:37:36.347 T:921805   error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=EMy_QuFEUZw]
2023-08-07 21:37:36.347 T:921805    info <general>: CVideoPlayer::OnExit()
2023-08-07 21:37:36.353 T:880936    info <general>: CVideoPlayer::CloseFile()
2023-08-07 21:37:36.355 T:880936    info <general>: VideoPlayer: waiting for threads to exit
```

On the UI I see: "One or more items failed to play. Check the log for more information about this message."

Usually I retry a few times and it works again.  This is on a regular Comcast internet connection, no VPNs or anything weird.

Can we make the plugin automatically retry on its own so this annoyance goes away?

### PR DESCRIPTION
**Pull request by MoojMidge**
Also includes:
* updates to enable HLS live streams using ISA
* updates to quality and stream feature selection
* improved handling of connection failures
* improved stream and language labelling
* option to separately enable/disable local and remote history tracking
* other stuff I have forgotten

### CODE REVIEW

**Comment by prometheanfire** [comment]
not sure what the fix was (haven't bisected) but this fixed my current 403 issue

**Comment by MoojMidge** [comment]
That's good, but what 403 issue?

If it was when you were trying to play a video it is probably fixed by [this](https://github.com/anxdpanic/plugin.video.youtube/pull/506/commits/80a54d02006fe6ba29546cf67abf889d4616e8bd#diff-e7bf74b573202709a6a20da1037ebb2d3b62c00e26aa18feca0214020a92d53fR606)

If it was when you were searching or opening a channel or playlist then I'm not sure which specific change fixed that as it was somewhat intermittent and I was never sure if it just went away because of some YouTube change.

**Comment by prometheanfire** [comment]
ya, that seems to be it

**Comment by jaylinski** [comment]
> not sure what the fix was (haven't bisected) but this fixed my current 403 issue

Can confirm, this fixes my 403 errors too (which resulted in a buzzing sound after about 12 seconds into the video and a frozen video). Did not happen on every video and sometimes a restart of Kodi helped, but the issue got worse in the last few weeks.

Thanks @MoojMidge !

**Pull request merged**
