### PR TITLE
Add live links resolving

### PR DESCRIPTION
**Pull request by danielkucera**
Adds resolving live links in format <youtube>/live/<video_id>.*

### CODE REVIEW

**Comment by MoojMidge** [comment]
Do you make use of the ability to load this plugin as a module to resolve Youtube urls?

I think utilising the url resolver and converter, that is used by the main plugin, would be a better way to extend the functionality of the module, if you are willing to give it a go?

**Comment by danielkucera** [comment]
I got lost... I thought this would solve my issue but it doesn't.
When I play live links, it ends like this:
```
2024-03-28 23:28:23.762 T:3663     info <general>: VideoPlayer::OpenFile: https://youtube.com/live/2l2to5giV0w
2024-03-28 23:28:23.959 T:6740     info <general>: Creating InputStream
2024-03-28 23:28:25.834 T:6740     info <general>: Creating Demuxer
2024-03-28 23:28:26.400 T:6740    error <general>: Open - error probing input format, https://consent.youtube.com/ml?continue=https://www.youtube.com/live/2l2to5giV0w?cbrd%3D1&gl=SK&hl=sk
&cm=2&pc=yt&src=1
2024-03-28 23:28:26.400 T:6740    error <general>: OpenDemuxStream - Error creating demuxer
```
Which part of the code should I adjust?

**Comment by MoojMidge** [comment]
> Which part of the code should I adjust?

You don't need to, it already fully works, but you are not using this plugin.

If you have a problem, open an issue next time and provide the requested details.

It is not clear what you are trying to achieve, or how exactly, but from the snippet of the log, you are trying to use Kodi to open a website url.

Have a read here https://github.com/anxdpanic/plugin.video.youtube/issues/579#issuecomment-2016876465 for some related discussion.

Kodi is not a web browser, and assumes that the url you are providing it is a video stream url and tries to play it, which obviously won't work.

**Comment by danielkucera** [comment]
@MoojMidge , sorry for bothering, this is actually the answer to my problem:
https://github.com/xbmc/Kore/pull/1010#issuecomment-2017165082

**Comment by MoojMidge** [comment]
No problem, hopefully the changes can be made to Kore to resolve the problem.

**Pull request closed without merging**
