### PR TITLE
New client fixes

### PR DESCRIPTION
**Pull request by MoojMidge**
A few more fixes. Not well tested, but don't have any more time.

- Fixes issue with subtitles that sometimes occurs when using the newer clients
- New default client that support VP9 HDR
- A couple of different fallbacks added
- Removed broken TV and web clients (needs a JS interpreter for the nsig handling)

### CODE REVIEW

**Comment by anxdpanic** [comment]
Thanks @MoojMidge 

Can you revert/delete the elevate level of log messages commit? Everything else looks great.

log notice will get pushback on official repository, so better to stay at debug

**Comment by MoojMidge** [comment]
Sure. I thought it might help identify future breakage, but I ended up removing the clients that would trigger those log messages anyway.

**Comment by RNavega** [comment]
> - Removed broken TV and web clients (needs a JS interpreter for the nsig handling)

Just for future reference, yt-dlp has a Python-based minimal interpreter for Javascript in here:  
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/jsinterp.py

That'd be a smaller dependency than what a full import of JS2PY would be.

**Comment by MoojMidge** [comment]
I had a look at the usual suspects for how they handled things, but going down that path was more effort than I had the time for.

For the moment the Android clients seem to be working (who knows for how long). Maybe those other clients will be required again in the future?

**Pull request merged**
