### PR TITLE
Update video_info.py

### PR DESCRIPTION
**Pull request by RNavega**
This fixes live video playback after those new API changes. There was a typo in the code that was causing the live stream headers to get mangled.  

This doesn't yet fix age-gated videos.

### CODE REVIEW

**Comment by anxdpanic** [comment]
@RNavega I simplified things here, https://github.com/anxdpanic/plugin.video.youtube/pull/218 looks like the included v1 key works with the endpoint. 

I will see about adding dual login back, so we can generate a v1 access token again when I have some time. If that's something you're interested in looking at I can help point you to the old implementation, might be able to revert some/all of it.

**Comment by RNavega** [comment]
@anxdpanic I'll take a look at 218, thank you for taking the time. 

I've found out why the OAuth use was broken, it's because our personal API keys aren't allowed to use this internal innertube API that the YT apps use. So we were trying to use it with a token for a different API.

Some brilliant people have charted how to use some of innertube, here are my references:
- https://github.com/pytube/pytube/blob/master/pytube/innertube.py
- https://github.com/OpenJarbas/tutubo
- https://github.com/tombulled/innertube  
- https://github.com/89z/mech/tree/master/youtube (edit: forgot this one)

There could be a complete overhaul of plugin.video.youtube to use this innertube API instead of the old YT Data API like it is now.  
The only concern, and I don't know how you'd feel about this,  is that we'd all be using the same API key/client secret/client ID taken from the "YT for TV" app as seen in the pytube code, camouflaging as that official app. This might be considered underhanded lol

**Comment by anxdpanic** [comment]
At one time the add-on did use the YouTube for TV API in combination with the data. 
It was removed, https://github.com/anxdpanic/plugin.video.youtube/commit/b7c0c9f87ee9633c1391634262f1e13630981692

And I've added the API key that we used then, which is already in the files. https://github.com/anxdpanic/plugin.video.youtube/pull/218/files#diff-5ecde54fa534f31c07c435544e8497cb462674901a9d688be492bfbbde50b579R100

API Keys: https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/__init__.py#L12

So that's about all that would be required

**Comment by RNavega** [comment]
> So that's about all that would be required

Oh, if I get what you're saying, even after the user authenticates w/ their own personal YT Data API key, we can get their access token, plus the _internal API key_ to play age-gated videos, access private library (My Subscriptions) etc.  
If that works then that'd be awesome.

The only thing left is that I saw [someone reporting a problem with lack of subtitles](https://github.com/anxdpanic/plugin.video.youtube/issues/211#issuecomment-944474782), I'd like to check on that.

**Comment by jmh2002** [comment]
> Oh, if I get what you're saying, even after the user authenticates w/ their own personal YT Data API key, we can get their access token, plus the _internal API key_ to play age-gated videos, access private library (My Subscriptions) etc. If that works then that'd be awesome.

I think that is how the addon used to work isn't it? And that's why we used to have to sign in / authorise twice? Once via YT for TV to get My Subscriptions, and once via our own API keys to get everything else?

> 
> The only thing left is that I saw [someone reporting a problem with lack of subtitles](https://github.com/anxdpanic/plugin.video.youtube/issues/211#issuecomment-944474782), I'd like to check on that.

I'm using Alpha 2 _without_ the latest patch from a few hours ago and I can confirm that there didn't seem to be any change to subtitle functionality.

I have always had subtitles enabled, and they continue to work on Kodi 19.1 with Alpha 1 and 2.

THANKS for all your work here @RNavega 

And THANKS to you too of course @anxdpanic 

👍👍👍

**Comment by anxdpanic** [comment]
Secondary login add back in https://github.com/anxdpanic/plugin.video.youtube/pull/219

It fixes some age-gated videos but not all, haven't had time to test My Channel yet.

**Comment by RNavega** [comment]
Thanks for porting the old code back in, @anxdpanic.

**Comment by anxdpanic** [comment]
Thankfully, the reverting went pretty smoothly so things went nice and quick 👍

**Pull request merged**
