### PR TITLE
Comments display fixed for a video item

### PR DESCRIPTION
**Pull request by ramateur**
Comments for a video didn't show due to str decode error

### CODE REVIEW

**Comment by anxdpanic** [comment]
which version of Kodi was this for?

**Comment by ramateur** [comment]
This fix is for 19.1. In 18 version everything was OK with displaying
comments in Russian locale. In 19 there was an error converting bytes
variable to str.

вс, 22 авг. 2021 г., 23:02 anxdpanic ***@***.***>:

**Comment by anxdpanic** [comment]
was this change tested in Kodi 18 as well? Just want want to confirm since `.decode` and `.encode` are usually required for python 2 or 3, not often both 👍

**Comment by ramateur** [comment]
No I didn't test it in 18. Just fix error in 19.

вс, 22 авг. 2021 г., 23:18 anxdpanic ***@***.***>:

**Comment by anxdpanic** [comment]
Thanks, I'll make the necessary adjustments after merge then 👍

**Comment by ramateur** [comment]
Hello
I just updated the Youtube plugin to version 6.8.17 and comments failed
again with this error (Kodi-19.1):
2021-08-31 12:03:57.307 T:9272     INFO <general>: initializing python
engine.
2021-08-31 12:03:57.310 T:9272     INFO <general>: [plugin.video.youtube]
Running: YouTube (6.8.17+matrix.1) on Matrix (Kodi-19.1) with Python 3.8.5
                                                    Path:
/special/parent_comments/
                                                    Params: {'video_id':
'iH11NXs7IrA'}
2021-08-31 12:03:57.745 T:9272    ERROR <general>: EXCEPTION Thrown
(PythonToCppException) : -->Python callback/script returned the following
error<--
                                                    - NOTE: IGNORING THIS
CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class
'AttributeError'>
                                                   Error Contents: module
'youtube_plugin.kodion.utils' has no attribute 'to_str'
                                                   Traceback (most recent
call last):
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\default.py",
line 15, in <module>

 runner.run(__provider__)
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\runner.py",
line 60, in run

 __RUNNER__.run(provider, context)
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_runner.py",
line 33, in run
                                                       results =
provider.navigate(context)
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py",
line 105, in navigate
                                                       result =
method(context, re_match)
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\register_provider_path.py",
line 19, in wrapper
                                                       return func(*args,
**kwargs)
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py",
line 796, in _on_yt_specials
                                                       return
yt_specials.process(category, self, context)
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_specials.py",
line 322, in process
                                                       return
_process_parent_comments(provider, context)
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_specials.py",
line 42, in _process_parent_comments

 result.extend(v3.response_to_items(provider, context, json_data))
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\v3.py",
line 294, in response_to_items

 result.extend(_process_list_response(provider, context, json_data))
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\v3.py",
line 199, in _process_list_response

 result.append(utils.make_comment_item(context, provider, snippet,
item_uri, total_replies))
                                                     File
"C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\utils.py",
line 49, in make_comment_item
                                                       author =
'[B]{}[/B]'.format(kodion.utils.to_str(snippet['authorDisplayName']))
                                                   AttributeError: module
'youtube_plugin.kodion.utils' has no attribute 'to_str'
                                                   -->End of Python script
error report<--

2021-08-31 12:03:57.951 T:9272     INFO <general>: Python interpreter
stopped
2021-08-31 12:03:57.965 T:3392    ERROR <general>: Skipped 2 duplicate
messages..
2021-08-31 12:03:57.965 T:3392    ERROR <general>:
XFILE::CDirectory::GetDirectory - Error getting
plugin://plugin.video.youtube/special/parent_comments/?video_id=iH11NXs7IrA
2021-08-31 12:03:58.065 T:3784    ERROR <general>:
CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/parent_comments/?video_id=iH11NXs7IrA)
failed


вс, 22 авг. 2021 г. в 23:37, anxdpanic ***@***.***>:

**Pull request merged**
