### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by hevet**

### CODE REVIEW

**Comment by MoojMidge** [comment]
Thanks for the contribution.

Unfortunately translation updates are not handled directly in this repository.

It is a bit of extra work, but can you have a look at https://github.com/anxdpanic/plugin.video.youtube/issues/187 to see how to submit the translations via WebLate? Thanks,

**Comment by hevet** [comment]
> Thanks for the contribution.
> 
> Unfortunately translation updates are not handled directly in this repository.
> 
> It is a bit of extra work, but can you have a look at #187 to see how to submit the translations via WebLate? Thanks,

The translation on weblate is blocked, so I made it here.

**Comment by anxdpanic** [comment]
@hevet Can you be more concise in how it's blocked? I can look into helping get that resolved

**Comment by hevet** [comment]
> @hevet Can you be more concise in how it's blocked? I can look into helping get that resolved

https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/#alerts

**Comment by hevet** [comment]
Unfortunately, I'm still blocked.

**Comment by anxdpanic** [comment]
@hevet Thanks, it's being looked into. I tried to resolve it, but it will need someone with more permissions. Will keep you posted here.

**Comment by anxdpanic** [comment]
@hevet Weblate translation is possible again thanks to @gade01 Please update the translation there, and we'll get it merge! 
Huge thanks for you patience and help translating!

**Review by ahmadmiz — APPROVED** [review]

**Pull request closed without merging**
