### PR TITLE
Follow up to #452

### PR DESCRIPTION
**Pull request by MoojMidge**
Adds additional embedded client fallback and signature deciphering for web client

Also adds the range query parameter which might help the throttling

### CODE REVIEW

**Review by HeresJonny — COMMENTED** [review]
Tried this commit on Nexus and Omega and throttling/buffering still takes place. Also, with MPEG-Dash disabled video will not play at all.
Update: 720p with MPEG-Dash plays without buffering.

**Comment by MoojMidge** [comment]
Yeah it's strange. I was able to replicate the rate limiting using the `TVHTML5_SIMPLY_EMBEDDED_PLAYER` client but the `ANDROID` client still works fine for me.

Quite a few people in #442 are reporting that using `ANDROID_EMBEDDED_PLAYER` is the only thing that works for them, so I added an option to choose between `ANDROID` and `ANDROID_EMBEDDED_PLAYER` (default).

Does this work any better?

**Comment by xyzfre** [comment]
I only use YT addon for trailers, I tried this version on a Windows 10 ,Nexus with AH2 and so far it's working perfect thank you so much for all your hard work💯💯 ,, feels great to be able to watch my trailers again❤️

**Comment by anxdpanic** [comment]
@MoojMidge 

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1650

This is what is required to resolve throttling. youtube-dl's license allows us to port that code over if someone has the time

**Comment by MoojMidge** [comment]
@anxdpanic - I am far from familiar with the topic but from what I can see the throttling is only happening when using `TVHTML5_SIMPLY_EMBEDDED_PLAYER`. When using the `ANDROID` and `ANDROID_EMBEDDED_PLAYER` client the nsig handling should not be required (there is no `n` query param in the stream urls).

What is happening is that the `ANDROID` client is being blocked because of an incorrect user-agent and is falling back to `TVHTML5_SIMPLY_EMBEDDED_PLAYER`.

Easy enough to fix, but then another problem occurs where the connection to the server closes and re-opens but the server responds with a 403 error which results in the video stopping prematurely.

TODO:
- Fix user-agent.
- Use correct user-agent and client pair rather than single user-agent for all clients.
- Add nsig handling for `TVHTML5_SIMPLY_EMBEDDED_PLAYER`.
- Investigate server response to `ANDROID` client

**Pull request merged**
