### PR TITLE
New fanart/in-app icons

### PR DESCRIPTION
**Pull request by start2018**
Because YouTube TV recently applied new line icons in their app, I upgraded those files.
I can't create indexed PNG but still tried to optimize images.

### CODE REVIEW

**Comment by anxdpanic** [comment]
@papercore-dev where did these new icons come from? were they created by you, or downloaded from somewhere?

**Comment by start2018** [comment]
> @papercore-dev where did these new icons come from? were they created by you, or downloaded from somewhere?

Extracted from Youtube for TV (It is actually web-based and could easily bypassed by using Tizen useragent).
Those are in OTF format and is using non standard unicode.

**Comment by Ch1llb0** [comment]
This looks like a nice update of the look of this addon 👍🏻

**Comment by piejanssens** [comment]
@anxdpanic Can we get this in please?
I was thinking that there was a rendering bug in Kodi, but it turns out to be a [disastrous resolution for this add-on's fanart](https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/media/fanart.jpg) 😄

**Comment by start2018** [comment]
> @anxdpanic Can we get this in please? I was thinking that there was a rendering bug in Kodi, but it turns out to be a [disastrous resolution for this add-on's fanart](https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/media/fanart.jpg) 😄

It's blur, maybe made to decrease conflicts with UI.

**Pull request merged**
