### PR TITLE
New YouTube Logo

### PR DESCRIPTION
**Pull request by start2018**
Updated youtube logo into 2014? version => 2021 version which is currently being used by YT desktop and TV.
No changes in in-app youtube logo.

### CODE REVIEW

**Comment by liroy788** [comment]
> _No description provided._

**Comment by start2018** [comment]
added.

**Comment by liroy788** [comment]
> Updated youtube logo into 2014? version => 2021 version which is currently being used by YT desktop and TV.
> No changes in in-app youtube logo.

**Comment by liroy788** [comment]
Hcz

**Comment by anxdpanic** [comment]
Thanks @papercore-dev~

Would you be able to make these;
icon: `512 x 512 indexed png`
fanart: `3840 x 2160 indexed png`

indexed png should keep them small since they are not colorful and don't have any large gradients
If you're not interested in doing that, just let me know.

**Comment by start2018** [comment]
> Thanks @papercore-dev~
> 
> Would you be able to make these;
> icon: `512 x 512 indexed png`
> fanart: `3840 x 2160 indexed png`
> 
> indexed png should keep them small since they are not colorful and don't have any large gradients
> If you're not interested in doing that, just let me know.

As I'm not using such an image tool to make those icons, I am unable to do so.

**Comment by liroy788** [comment]
> Thanks @papercore-dev~
> 
> Would you be able to make these;
> icon: `512 x 512 indexed png`
> fanart: `3840 x 2160 indexed png`
> 
> indexed png should keep them small since they are not colorful and don't have any large gradients
> If you're not interested in doing that, just let me know.

Uczę się

**Comment by start2018** [comment]
> > Thanks @papercore-dev~
> > Would you be able to make these;
> > icon: `512 x 512 indexed png`
> > fanart: `3840 x 2160 indexed png`
> > indexed png should keep them small since they are not colorful and don't have any large gradients
> > If you're not interested in doing that, just let me know.
> 
> Uczę się

Could you use English? I can't understand what Hcz and those sentences mean :/
Czy możesz używać angielskiego? Nie rozumiem co oznaczają Hcz i te zdania :/

**Comment by anxdpanic** [comment]
Thanks @papercore-dev

**Pull request merged**
