### PR TITLE
7.0.2.1

### PR DESCRIPTION
**Pull request by MoojMidge**
Update workflows to correct Matrix InputStream.Adaptive dependency version

### CODE REVIEW

**Comment by doraskayo** [comment]
@MoojMidge, I think this wasn't released to the official repos, possibly because of this issue: https://github.com/anxdpanic/plugin.video.youtube/actions/runs/6167484626/job/16738521404

**Comment by MoojMidge** [comment]
It's all good, nothing of concern here.

v7.0.2.1 only has a Kodi Matrix specific change, made as a quick post release fix after v7.0.2

The error in the workflow is just indicating that there is already an existing PR for the plugin in the Nexus repository. A subsequent PR for the Matrix repository has also already been created.

It will just take some time for the PRs to be reviewed/approved/merged before the release appears in the official Kodi plugin repository.

**Comment by bkuhls** [comment]
Afaics addon.xml in plugin.video.youtube-7.0.2.2.matrix.**unofficial**.1.zip still contains
```
<import addon="inputstream.adaptive" version="20.3.1"/>
```
plugin.video.youtube-7.0.2.2.matrix.1.zip is fine

**Comment by MoojMidge** [comment]
Yeah, unfortunately I only noticed a little while back, after this was released.

I tried to get some people to test the Matrix versions, as they were otherwise untested (by me), however the only people who provided any feedback for it were two people using Kodi 20 (Nexus) who installed it by accident, and one person who tested 7.0.2.1.matrix.1, so it got missed.

In the meantime, it's fixed in https://github.com/MoojMidge/plugin.video.youtube/commit/2b82ca1637fbaac7661a066f910b9f17174dd3e0, but thanks for the reminder - there are also a few other minor bug fixes that need to be PR'ed.

**Comment by bkuhls** [comment]
> I tried to get some people to test the Matrix versions, as they were otherwise untested (by me), 

Meanwhile I could install https://github.com/anxdpanic/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-7.0.2.2.matrix.1.zip

Thanks for pointing out to the additional fixes in your repo of which https://github.com/MoojMidge/plugin.video.youtube/commit/b9296e699ad0cf21c2e69d2afdf777e11b273e8a is really needed as it fixes

```
2023-10-29 12:53:21.453 T:14730    info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2+matrix.1) on Matrix (Kodi-19.5) with Python 3.9.18
[...]
Error Contents: _get() got an unexpected keyword argument 'language_name'
```
I also installed the rest of your fixes and I am testing right now...

**Pull request merged**
